### ISSUE TITLE
Popup list shows archived items; context menu option is now unreliable

### ISSUE THREAD

**Issue by anotherjames** [diegonakamashi/ril-chrome#50]
Maybe this is two separate issues really, but I wonder if it's really down to a single cause like something changing about pocket's API?

1. When opening the popup list, archived items show as well as current saves.
2. The right-click context menu option doesn't appear to work well either - though perhaps it just isn't updating the list / showing success correctly, as pages saved through it do show up on https://getpocket.com/my-list . (Maybe that also suggests a problem with refreshing the list?)

I tried a different chrome extension, but it seemed to have issues too, which made me wonder about pocket's API too.

**Comment by stjacob** [comment]
The same issue with yours.  This plugin doesn't work well after I updated the newest version of Edge/Chrome browser. Mine is 126.0.2592.102 Edge.

**Comment by anotherjames** [comment]
Looks like this was solved in https://github.com/diegonakamashi/ril-chrome/commit/2877d5783901d8814a184f32853c8b6760590630; thank you!
